services:
  utterancer:
    build:
      context: .
      network: host
    network_mode: "host"
    env_file:
      - .env
    volumes:
      - ${PWD}:/workspace
      - ${PWD}/.cache:/root/.cache
    working_dir: /workspace
    entrypoint:
      - /bin/bash
    stdin_open: true
    shm_size: '16gb'
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
